### ISSUE TITLE
I am not able to see the log after i use the Datadog handler

### ISSUE THREAD

**Issue by gsubha111** [ustudio/datadog-logger#7]
Hi 
I follwed the steps which you have given.But after running the script i can not see the any update in Datadog .Can you please help me

**Comment by spiralman** [comment]
@gsubha111 Hello, sorry we missed this issue request. Given its age, we're going to close it. However, if you do still need help debugging this issue, feel free to re-open it, but note that we'll need a sample script (without any credentials, of course) and any output you're getting when you run the script.

Also note that, since this library was initially developed, Datadog now supports log ingestion as a general feature, which might be more suited to your needs.
